DELIMITER $$

CREATE FUNCTION average5(Num1 INT, Num2 INT, Num3 INT, Num4 INT, Num5 INT)
RETURNS FLOAT DETERMINISTIC
BEGIN
    RETURN (Num1 + Num2 + Num3 + Num4 + Num5) / 5.0;
END $$

DELIMITER ;


SELECT average5(1, 2, 3, 4, 5);
